// components/dashboard/new-demo-modal.tsx

import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { UploadCloud } from "lucide-react";

type NewDemoModalProps = {
    isOpen: boolean;
    onOpenChange: (isOpen: boolean) => void;
};

export default function NewDemoModal({ isOpen, onOpenChange }: NewDemoModalProps) {
    return (
        <Dialog open={isOpen} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[480px]">
                <DialogHeader>
                    <DialogTitle className="text-xl">Create a new demo</DialogTitle>
                    <DialogDescription>
                        Upload the recording file generated by the DemoSnap Chrome extension.
                    </DialogDescription>
                </DialogHeader>

                <div className="py-6">
                    <div className="flex flex-col items-center justify-center w-full h-48 border-2 border-dashed border-slate-300 rounded-lg cursor-pointer bg-slate-50 hover:bg-slate-100 transition-colors">
                        <UploadCloud className="h-10 w-10 text-slate-400 mb-3" />
                        <p className="text-slate-700 font-semibold">
                            Drag & drop your <span className="text-emerald-500 font-bold">.demosnap.json</span> file
                        </p>
                        <p className="text-xs text-slate-500 mt-1">or click to browse</p>
                        {/* L'input est caché mais fonctionnel */}
                        <input type="file" className="hidden" accept=".demosnap.json" />
                    </div>
                </div>

                <DialogFooter>
                    <Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button>
                    {/* Le bouton sera désactivé jusqu'à ce qu'un fichier soit sélectionné */}
                    <Button disabled className="bg-emerald-500 hover:bg-emerald-600">Create Demo</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}